name: "Daily(26.04): lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  resolute-lxd_container:
    uses: ./.github/workflows/11-dispatch-common.yml
    with:
      release: resolute
      platform: lxd_container
