name: "Daily(25.10): lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  questing-lxd_container:
    uses: ./.github/workflows/11-dispatch-common.yml
    with:
      release: questing
      platform: lxd_container
