name: "Daily(24.04): lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  noble-lxd_container:
    uses: ./.github/workflows/11-dispatch-common.yml
    with:
      release: noble
      platform: lxd_container
