name: "Daily(22.04): lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  jammy-lxd_container:
    uses: ./.github/workflows/11-dispatch-common.yml
    with:
      release: jammy
      platform: lxd_container
